### ISSUE TITLE
Conflicting property name definitions: 'lastRenewalTimestamp'

### ISSUE THREAD

**Issue by karlwanghn** [Netflix/eureka#1011]
when i deploy a war eureka app to weblogic,problems happend.

Caused by: java.lang.IllegalStateException: Conflicting property name definitions: 'lastRenewalTimestamp' (for [method com.netflix.appinfo.LeaseInfo#getRenewalTimestamp(0 params)]) vs 'renewalTimestamp' (for [parameter #4, annotations: {interface com.fasterxml.jackson.annotation.JsonProperty=@com.fasterxml.jackson.annotation.JsonProperty(value=renewalTimestamp, required=false)}])
	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.findRenamed(POJOPropertyBuilder.java:694) ~[com.fasterxml.jackson.core.jackson-databind.jar:2.3.2]
	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.findNewName(POJOPropertyBuilder.java:673) ~[com.fasterxml.jackson.core.jackson-databind.jar:2.3.2]
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._renameProperties(POJOPropertiesCollector.java:682) ~[com.fasterxml.jackson.core.jackson-databind.jar:2.3.2]
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collect(POJOPropertiesCollector.java:242) ~[com.fasterxml.jackson.core.jackson-databind.jar:2.3.2]
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.collectProperties(BasicClassIntrospector.java:142) ~[com.fasterxml.jackson.core.jackson-databind.jar:2.3.2]
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forSerialization(BasicClassIntrospector.java:68) ~[com.fasterxml.jackson.core.jackson-databind.jar:2.3.2]
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forSerialization(BasicClassIntrospector.java:11) ~[com.fasterxml.jackson.core.jackson-databind.jar:2.3.2]
	at com.fasterxml.jackson.databind.SerializationConfig.introspect(SerializationConfig.java:530) ~[com.fasterxml.jackson.core.jackson-databind.jar:2.3.2]
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:133) ~[com.fasterxml.jackson.core.jackson-databind.jar:2.3.2]
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1077) ~[com.fasterxml.jackson.core.jackson-databind.jar:2.3.2]
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1037) ~[com.fasterxml.jackson.core.jackson-databind.jar:2.3.2]
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:445) ~[com.fasterxml.jackson.core.jackson-databind.jar:2.3.2]
	at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:599) ~[com.fasterxml.jackson.core.jackson-databind.jar:2.3.2]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:93) ~[com.fasterxml.jackson.core.jackson-databind.jar:2.3.2]
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1837) ~[com.fasterxml.jackson.core.jackson-databind.jar:2.3.2]
	at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:261) ~[com.fasterxml.jackson.core.jackson-core.jar:2.3.2]
	at com.fasterxml.jackson.core.JsonGenerator.writeObjectField(JsonGenerator.java:1312) ~[com.fasterxml.jackson.core.jackson-core.jar:2.3.2]
	at com.netflix.discovery.converters.EurekaJacksonCodec$InstanceInfoSerializer.serialize(EurekaJacksonCodec.java:358) ~[eureka-client-1.6.2.jar:1.6.2]
	at com.netflix.discovery.converters.EurekaJacksonCodec$InstanceInfoSerializer.serialize(EurekaJacksonCodec.java:316) ~[eureka-client-1.6.2.jar:1.6.2]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:237) ~[com.fasterxml.jackson.core.jackson-databind.jar:2.3.2]
	... 48 common frames omitted

**Comment by qiangdavidliu** [comment]
Hi @karlwanghn you might need to update to a version of jackson that is greater than 2.3.2. Eureka currently comes with a jackson dependency of 2.8.7.
