### ISSUE TITLE
Eureka : Connection Refused when we set eureka.client.register-with-eureka=true

### ISSUE THREAD

**Issue by basiths** [Netflix/eureka#1024]
Hi, 

I need to setup the Eureka with high availability (2 nodes). Can you please have a look at the below configuration and let me know if this enables the replication and high availability for eureka.

eureka-application.properties from node1:

spring.profiles=hostname01.corp.com
server.address=hostname01.corp.com

eureka.environment=test
eureka.datacenter=dc
eureka.name=eureka
server.contextPath=/eureka
spring.application.name=eureka-service

eureka.server.registry-sync-retry-wait-ms=500
eureka.server.registry-sync-retries=3
eureka.server.a-sgcache-expiry-timeout-ms=60000
eureka.server.eviction-interval-timer-in-ms=30000
eureka.server.peer-eureka-nodes-update-interval-ms=15000
eureka.server.renewal-threshold-update-interval-ms=300000
eureka.server.enableSelfPreservation=true

eureka.client.healthcheck.enabled=true
eureka.client.prefer-same-zone-eureka=true
eureka.client.serviceUrl.defaultZone=http://hostname01.corp.com/eureka/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

endpoints.shutdown.sensitive=false
endpoints.shutdown.enabled=true

eureka.instance.appname=${spring.application.name}
eureka.instance.preferIpAddress=false
endpoints.health.sensitive=false
spring.cloud.config.discovery.enabled=true

eureka-application.properties from node2:

spring.profiles=hostname02.corp.com
server.address=hostname02.corp.com

eureka.environment=test
eureka.datacenter=dc
eureka.name=eureka
server.contextPath=/eureka
spring.application.name=eureka-service

eureka.server.registry-sync-retry-wait-ms=500
eureka.server.registry-sync-retries=3
eureka.server.a-sgcache-expiry-timeout-ms=60000
eureka.server.eviction-interval-timer-in-ms=30000
eureka.server.peer-eureka-nodes-update-interval-ms=15000
eureka.server.renewal-threshold-update-interval-ms=300000
eureka.server.enableSelfPreservation=true

eureka.client.healthcheck.enabled=true
eureka.client.prefer-same-zone-eureka=true
eureka.client.serviceUrl.defaultZone=http://hostname02.corp.com/eureka/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

endpoints.shutdown.sensitive=false
endpoints.shutdown.enabled=true

eureka.instance.appname=${spring.application.name}
eureka.instance.preferIpAddress=false
endpoints.health.sensitive=false
spring.cloud.config.discovery.enabled=true

Questions : 
i) If I use eureka.client.serviceUrl.defaultZone=http://hostname02.corp.com/eureka/eureka/ in node1, while starting the instance, its giving connection refused then connecting it after some time. Can we fix this behavior.

ii) If I use eureka.instance.hostName=hostname01.corp.com parameter in node1, the DS replication is not working.

iii) The eureka portal is not displaying the available-replicas. Because Instances currently registered with Eureka" is registering the client as "hostname02" instead of "hostname02.corp.com". Is there a option to fix this.

iv) If I set eureka.client.fetch-registry=true, during the startup its throwing the connection refused exception.

2017-12-15 22:52:12.254  WARN 27995 --- [           main] c.n.d.s.t.d.RetryableEurekaHttpClient    : Request execution failure
2017-12-15 22:52:12.256 ERROR 27995 --- [           main] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_EUREKA-SERVICE/hostname01:eureka-service:10080 - was unable to refresh its cache! status = Cannot execute request on any known server

com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
        at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:111) ~[eureka-client-1.4.12.jar!/:1.4.12]
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134) ~[eureka-client-1.4.12.jar!/:1.4.12]
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137) ~[eureka-client-1.4.12.jar!/:1.4.12]
        at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77) ~[eureka-client-1.4.12.jar!/:1.4.12]
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134) ~[eureka-client-1.4.12.jar!/:1.4.12]
        at com.netflix.discovery.DiscoveryClient.getAndStoreFullRegistry(DiscoveryClient.java:1030) [eureka-client-1.4.12.jar!/:1.4.12]
        at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:944) [eureka-client-1.4.12.jar!/:1.4.12]
        at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:444) [eureka-client-1.4.12.jar!/:1.4.12]
        at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:304) [eureka-client-1.4.12.jar!/:1.4.12]

Can you please help me to fix this issues.

**Comment by qiangdavidliu** [comment]
Hi @basiths please check to see if this document help to address your questions:
http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_peer_awareness

Thanks.
