### ISSUE TITLE
Client reports "HTTP 400 Bad Request/unable to send heartbeart!" even though heartbeat succeeds

### ISSUE THREAD

**Issue by jbrew8** [Netflix/eureka#1186]
I have setup a eureka server and a handful of web services as eureka clients, all deployed as aws elastic beanstalk apps. Everything appears to be working correctly- the apps register with eureka and are visible on the system status page, and I can hit them via a zuul server that gets routing info from eureka.

However, the clients are reporting that they are not able to send heartbeats, despite the fact that the server is receiving them just fine. The server lists the services as UP and the access log for the server shows that it is receiving the heartbeats and replying with a 200 status code. 

But the clients are are throwing 400/Bad Request exceptions:

```
2019-03-08 15:38:11,884 [DiscoveryClient-HeartbeatExecutor-0] DEBUG c.n.d.s.t.j.AbstractJerseyEurekaHttpClient - Jersey HTTP PUT <eureka server host>/eureka/apps/HOOPLA-RECOMMENDATIONS/<hostname>:80:3aaeab0f-8899-4890-9323-584cf416aec2; statusCode=200
2019-03-08 15:38:11,884 [DiscoveryClient-HeartbeatExecutor-0] ERROR c.n.d.s.t.d.RedirectingEurekaHttpClient - Request execution error. endpoint=DefaultEndpoint{ serviceUrl='<eureka server host>/eureka}
javax.ws.rs.WebApplicationException: HTTP 400 Bad Request
	at com.netflix.discovery.provider.DiscoveryJerseyProvider.readFrom(DiscoveryJerseyProvider.java:110)
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:634)
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:586)
	at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.sendHeartBeat(AbstractJerseyEurekaHttpClient.java:105)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92)
	at com.netflix.discovery.shared.transport.decorator.MetricsCollectingEurekaHttpClient.execute(MetricsCollectingEurekaHttpClient.java:73)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92)
	at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.executeOnNewServer(RedirectingEurekaHttpClient.java:118)
	at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.execute(RedirectingEurekaHttpClient.java:79)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92)
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:120)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89)
	at com.netflix.discovery.DiscoveryClient.renew(DiscoveryClient.java:846)
	at com.netflix.discovery.DiscoveryClient$HeartbeatThread.run(DiscoveryClient.java:1405)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.thoughtworks.xstream.io.StreamException: 
	at com.thoughtworks.xstream.io.xml.DomDriver.createReader(DomDriver.java:115)
	at com.thoughtworks.xstream.io.xml.DomDriver.createReader(DomDriver.java:84)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1445)
	at com.netflix.discovery.converters.wrappers.CodecWrappers$XStreamXml.decode(CodecWrappers.java:387)
	at com.netflix.discovery.provider.DiscoveryJerseyProvider.readFrom(DiscoveryJerseyProvider.java:103)
	... 23 common frames omitted
Caused by: org.xml.sax.SAXParseException: Premature end of file.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at com.thoughtworks.xstream.io.xml.DomDriver.createReader(DomDriver.java:108)
	... 27 common frames omitted
2019-03-08 15:38:11,884 [DiscoveryClient-HeartbeatExecutor-0] WARN  c.n.d.s.t.d.RetryableEurekaHttpClient - Request execution failed with message: HTTP 400 Bad Request
2019-03-08 15:38:11,884 [DiscoveryClient-HeartbeatExecutor-0] ERROR c.netflix.discovery.DiscoveryClient - DiscoveryClient_HOOPLA-RECOMMENDATIONS/<hostname>:80:3aaeab0f-8899-4890-9323-584cf416aec2 - was unable to send heartbeat!
```

The client acknowledges the 200 response from the server, but then throws an error when trying to parse the response body. Stepping through the client code, it looks like the client is expecting an InstanceInfo object in the body of the response it gets from the server. But the heartbeat endpoint's response body is empty. 

The server and client are the same eureka version (1.9.3).

Is this the expected behavior? Is this a bug, or could there be a problem with my configuration?

**Comment by jbrew8** [comment]
In my original post I said everything appeared to be working fine despite the exceptions, but this was wrong: clients were not automatically re-registering with the server when the server was restarted.

But- this might not be a bug after all. I had eureka running as an aws elastic beanstalk app using tomcat and httpd. The httpd config had mod_deflate enabled, which appears to have caused all of the empty response bodies to be compressed into an empty gzip file. The discovery client through exceptions when trying to parse this empty response body. Disabling gzip compression on the eureka server solved this issue.

**Comment by bsushant-athena** [comment]
We are also seeing same issue and we want the compression as well. Isn't there any other workaround for this ?

**Comment by lishuai2016** [comment]
eureka:
  instance:
    hostname: localhost
  client:
    gZipContent: false
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:80/eureka/
  server:
    enableSelfPreservation: false  
    gZipContentFromRemoteRegion: false

We are also seeing same issue ,and accept you  tips, my config is show above. the error is always. please tell me where my error? thank you!

**Comment by lishuai2016** [comment]
@jbrew8

**Comment by DreamUFO** [comment]
netflix-eureka 2.1.2.RELEASE
in k8s environment with same issue 
know the problem but don't know how to fix it.
cause all of the empty response bodies to be compressed into an empty gzip file

**Comment by DreamUFO** [comment]
I have fixed this.
if your eureka server run by war deploy to tomcat,do not compression xml and json,setting in tomcat config server.xml
if your eureka server run by jar,do not compression  xml and json,setting in application.yml or application.properties or bootstrap.properties

**Comment by DMalonas** [comment]
Can you show what you mean by that, please?

**Comment by DreamUFO** [comment]
> Can you show what you mean by that, please? What is your configuration?


![QQ截图20200923193738](https://user-images.githubusercontent.com/10512112/94007728-78373700-fdd4-11ea-9800-3b5b38dbd96b.png)

remove these compression config from your web server  or application.yml.
this fixed my issue

**Comment by DMalonas** [comment]
My application.yml for the Eureka-Client, or for the Eureka-Server project?

**Comment by DreamUFO** [comment]
> My application.yml for the Eureka-Client, or for the Eureka-Server project?

Eureka-Server

**Comment by DMalonas** [comment]
> > My application.yml for the Eureka-Client, or for the Eureka-Server project?
> 
> Eureka-Server

Like below?
eureka.client.g-zip-content=false
eureka.server.g-zip-content-from-remote-region=false
eureka.server.xml-codec-name=false

**Comment by DreamUFO** [comment]
> > > My application.yml for the Eureka-Client, or for the Eureka-Server project?
> > 
> > 
> > Eureka-Server
> 
> Like below?
> eureka.client.g-zip-content=false
> eureka.server.g-zip-content-from-remote-region=false
> eureka.server.xml-codec-name=false

yes,if you run by jar.

**Comment by DMalonas** [comment]
> > > > My application.yml for the Eureka-Client, or for the Eureka-Server project?
> > > 
> > > 
> > > Eureka-Server
> > 
> > 
> > Like below?
> > eureka.client.g-zip-content=false
> > eureka.server.g-zip-content-from-remote-region=false
> > eureka.server.xml-codec-name=false
> 
> yes,if you run by jar.

I package a war and deploy that in the cloud.
My configuration is only a application.properties file
and a pom.xml

**Comment by DMalonas** [comment]
> > > > > My application.yml for the Eureka-Client, or for the Eureka-Server project?
> > > > 
> > > > 
> > > > Eureka-Server
> > > 
> > > 
> > > Like below?
> > > eureka.client.g-zip-content=false
> > > eureka.server.g-zip-content-from-remote-region=false
> > > eureka.server.xml-codec-name=false
> > 
> > 
> > yes,if you run by jar.
> 
> I package a war and deploy that in the cloud.
> My configuration is only a application.properties file
> and a pom.xml. Isnt application.properties ok for war?

**Comment by DreamUFO** [comment]
> > > > > > My application.yml for the Eureka-Client, or for the Eureka-Server project?
> > > > > 
> > > > > 
> > > > > Eureka-Server
> > > > 
> > > > 
> > > > Like below?
> > > > eureka.client.g-zip-content=false
> > > > eureka.server.g-zip-content-from-remote-region=false
> > > > eureka.server.xml-codec-name=false
> > > 
> > > 
> > > yes,if you run by jar.
> > 
> > 
> > I package a war and deploy that in the cloud.
> > My configuration is only a application.properties file
> > and a pom.xml. Isnt application.properties ok for war?

if you run by war,careful your web server,such as tomcat,in server.xml maybe have gzip compression config,remove it.

**Comment by DMalonas** [comment]
> server.xml

I dont have a server.xml file at all in my project

**Comment by DMalonas** [comment]
> > > > > > > My application.yml for the Eureka-Client, or for the Eureka-Server project?
> > > > > > 
> > > > > > 
> > > > > > Eureka-Server
> > > > > 
> > > > > 
> > > > > Like below?
> > > > > eureka.client.g-zip-content=false
> > > > > eureka.server.g-zip-content-from-remote-region=false
> > > > > eureka.server.xml-codec-name=false
> > > > 
> > > > 
> > > > yes,if you run by jar.
> > > 
> > > 
> > > I package a war and deploy that in the cloud.
> > > My configuration is only a application.properties file
> > > and a pom.xml. Isnt application.properties ok for war?
> 
> if you run by war,careful your web server,such as tomcat,in server.xml maybe have gzip compression config,remove it.

I dont have a server.xml file at all in my project

**Comment by DreamUFO** [comment]
> > server.xml
> 
> I dont have a server.xml file at all in my project

no,not in your project,that in your web server config.
does your war run in tomcat that provided by cloud

**Comment by DMalonas** [comment]
Changed to that:


    <Connector port="80" protocol="HTTP/1.1"
               connectionTimeout="20000"
	       compression="on"
               compressionMinSize="512"
	       useSendfile="false"
               compressableMimeType="text/html,text/xml,text/plain,text/css,application/xml,application/xhtml+xml,application/rss+xml,application/javascript,application/x-javascript,image/svg+xml"
               redirectPort="443" />
               
    <Connector port="8080" protocol="HTTP/1.1"
               connectionTimeout="20000"
	       compression="on"
               compressionMinSize="512"
	       useSendfile="false"
               compressableMimeType="text/html,text/xml,text/plain,text/javascript,text/plain,application/json,application/xml,text/css,application/xml,application/xhtml+xml,application/rss+xml,application/javascript,application/x-javascript,image/svg+xml"
               redirectPort="443" />

**Comment by DreamUFO** [comment]
yeah,same situation with me,
remove these configs 

compression="on"
compressionMinSize="512"
compressableMimeType="text/html,text/xml,text/plain,text/javascript,text/plain,application/json,application/xml,text/css,application/xml,application/xhtml+xml,application/rss+xml,application/javascript,application/x-javascript,image/svg+xml"

in your Connector

**Comment by DMalonas** [comment]
Like that?

<Connector port="80" protocol="HTTP/1.1"
           connectionTimeout="20000"
       useSendfile="false"
           redirectPort="443" />
           
<Connector port="8080" protocol="HTTP/1.1"
           connectionTimeout="20000"
       useSendfile="false"
           redirectPort="443" />

**Comment by DMalonas** [comment]
Like that?

<Connector port="80" protocol="HTTP/1.1"
           connectionTimeout="20000"
       useSendfile="false"
           redirectPort="443" />
           
<Connector port="8080" protocol="HTTP/1.1"
           connectionTimeout="20000"
       useSendfile="false"
           redirectPort="443" />

**Comment by DMalonas** [comment]
> yeah,same situation with me,
> remove these configs
> 
> compression="on"
> compressionMinSize="512"
> compressableMimeType="text/html,text/xml,text/plain,text/javascript,text/plain,application/json,application/xml,text/css,application/xml,application/xhtml+xml,application/rss+xml,application/javascript,application/x-javascript,image/svg+xml"
> 
> in your Connector

Like that?

<Connector port="80" protocol="HTTP/1.1"
           connectionTimeout="20000"
       useSendfile="false"
           redirectPort="443" />
           
<Connector port="8080" protocol="HTTP/1.1"
           connectionTimeout="20000"
       useSendfile="false"
           redirectPort="443" />

**Comment by DMalonas** [comment]
> > yeah,same situation with me,
> > remove these configs
> > compression="on"
> > compressionMinSize="512"
> > compressableMimeType="text/html,text/xml,text/plain,text/javascript,text/plain,application/json,application/xml,text/css,application/xml,application/xhtml+xml,application/rss+xml,application/javascript,application/x-javascript,image/svg+xml"
> > in your Connector
> 
> Like that?

<Connector port="80" protocol="HTTP/1.1"
         connectionTimeout="20000"
         useSendfile="false"
           redirectPort="443" />
           
<Connector port="8080" protocol="HTTP/1.1"
        connectionTimeout="20000"
       useSendfile="false"
         redirectPort="443" />

**Comment by DMalonas** [comment]
<Connector port="80" protocol="HTTP/1.1"
         connectionTimeout="20000"
         useSendfile="false"
           redirectPort="443" />
           
<Connector port="8080" protocol="HTTP/1.1"
        connectionTimeout="20000"
       useSendfile="false"
         redirectPort="443" />

**Comment by DMalonas** [comment]
<Connector port="80" protocol="HTTP/1.1"
         connectionTimeout="20000"
         useSendfile="false"
           redirectPort="443" />
           
<Connector port="8080" protocol="HTTP/1.1"
        connectionTimeout="20000"
       useSendfile="false"
         redirectPort="443" />

**Comment by DreamUFO** [comment]
leave this in your Connector config
<Connector port="8080" protocol="HTTP/1.1"
           connectionTimeout="20000"
       useSendfile="false"
           redirectPort="443" />

> > yeah,same situation with me,
> > remove these configs
> > compression="on"
> > compressionMinSize="512"
> > compressableMimeType="text/html,text/xml,text/plain,text/javascript,text/plain,application/json,application/xml,text/css,application/xml,application/xhtml+xml,application/rss+xml,application/javascript,application/x-javascript,image/svg+xml"
> > in your Connector
> 
> Like that?

leave this in your Connector config

<Connector port="8080" protocol="HTTP/1.1"
           connectionTimeout="20000"
       useSendfile="false"
           redirectPort="443" />
