### ISSUE TITLE
Deploy eureka on docker.

### ISSUE THREAD

**Issue by archsia** [Netflix/eureka#1449]
main class:

```
package com.sample.eureka

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
import org.springframework.cloud.netflix.eureka.server.EnableEurekaServer

@EnableEurekaServer
@SpringBootApplication
class EurekaApplication

fun main(args: Array<String>) {
    runApplication<EurekaApplication>(*args)
}
```

build.gradle:

```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import org.springframework.boot.gradle.tasks.bundling.BootBuildImage

plugins {
    id("org.springframework.boot") version "2.6.4"
    id("io.spring.dependency-management") version "1.0.11.RELEASE"
    kotlin("jvm") version "1.6.10"
    kotlin("plugin.spring") version "1.6.10"
    id("org.springframework.experimental.aot") version "0.11.3"
}

group = "com.garpix"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_11

repositories {
    maven { url = uri("https://repo.spring.io/release") }
    mavenCentral()
}

extra["springCloudVersion"] = "2021.0.1"

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.springframework.cloud:spring-cloud-starter-netflix-eureka-server:3.1.1")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.6.4")
}

dependencyManagement {
    imports {
        mavenBom("org.springframework.cloud:spring-cloud-dependencies:${property("springCloudVersion")}")
    }
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs = listOf("-Xjsr305=strict")
        jvmTarget = "11"
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
}

tasks.withType<BootBuildImage> {
    builder = "paketobuildpacks/builder:tiny"
    environment = mapOf("BP_NATIVE_IMAGE" to "true")
}
```
docker file:

```
FROM gradle:7.4.1-jdk11 AS build
COPY --chown=gradle:gradle . /code/src
WORKDIR /code/src
RUN gradle
RUN gradle build --no-daemon

FROM azul/zulu-openjdk:11.0.13-11.52.13

EXPOSE 8080

RUN mkdir /app

COPY --from=build /code/src/build/libs/eureka-0.0.1-SNAPSHOT.jar /app/application.jar 

WORKDIR /app

ENTRYPOINT ["java","-jar","application.jar"]
```
application.yml:
```
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
spring:
  application:
    name: eureka-server
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
```

Log:
````
2022-03-23 12:59:06.465  INFO 1 --- [           main] o.s.nativex.NativeListener               : AOT mode disabled



  .   ____          _            __ _ _


 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \


( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \


 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )


  '  |____| .__|_| |_|_| |_\__, | / / / /


 =========|_|==============|___/=/_/_/_/


 :: Spring Boot ::                (v2.6.4)



2022-03-23 12:59:06.662  INFO 1 --- [           main] com.garpix.eureka.EurekaApplicationKt    : Starting EurekaApplicationKt using Java 11.0.13 on a71e96594094 with PID 1 (/app/application.jar started by root in /app)


2022-03-23 12:59:06.664  INFO 1 --- [           main] com.garpix.eureka.EurekaApplicationKt    : No active profile set, falling back to 1 default profile: "default"


2022-03-23 12:59:08.011  INFO 1 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=6e85d966-b803-3612-8203-6581987d3218


2022-03-23 12:59:08.686  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)


2022-03-23 12:59:08.702  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]


2022-03-23 12:59:08.703  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.58]


2022-03-23 12:59:08.762  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext


2022-03-23 12:59:08.763  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2010 ms


2022-03-23 12:59:10.048  INFO 1 --- [           main] c.s.j.s.i.a.WebApplicationImpl           : Initiating Jersey application, version 'Jersey: 1.19.4 05/24/2017 03:20 PM'


2022-03-23 12:59:10.967 ERROR 1 --- [           main] c.s.j.s.i.a.RootResourceUriRules         : The ResourceConfig instance does not contain any root resource classes.


2022-03-23 12:59:10.978 ERROR 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Exception starting filter [servletContainer]



com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does not contain any root resource classes.


	at com.sun.jersey.server.impl.application.RootResourceUriRules.<init>(RootResourceUriRules.java:99) ~[jersey-server-1.19.4.jar!/:1.19.4]


	at com.sun.jersey.server.impl.application.WebApplicationImpl._initiate(WebApplicationImpl.java:1359) ~[jersey-server-1.19.4.jar!/:1.19.4]


	at com.sun.jersey.server.impl.application.WebApplicationImpl.access$700(WebApplicationImpl.java:180) ~[jersey-server-1.19.4.jar!/:1.19.4]


	at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:799) ~[jersey-server-1.19.4.jar!/:1.19.4]


	at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:795) ~[jersey-server-1.19.4.jar!/:1.19.4]


	at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193) ~[jersey-core-1.19.4.jar!/:1.19.4]


	at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:795) ~[jersey-server-1.19.4.jar!/:1.19.4]


	at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:790) ~[jersey-server-1.19.4.jar!/:1.19.4]


	at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:509) ~[jersey-servlet-1.19.4.jar!/:1.19.4]


	at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:339) ~[jersey-servlet-1.19.4.jar!/:1.19.4]


	at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:605) ~[jersey-servlet-1.19.4.jar!/:1.19.4]


	at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:207) ~[jersey-servlet-1.19.4.jar!/:1.19.4]


	at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:394) ~[jersey-servlet-1.19.4.jar!/:1.19.4]


	at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:744) ~[jersey-servlet-1.19.4.jar!/:1.19.4]


	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:272) ~[tomcat-embed-core-9.0.58.jar!/:na]


	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:106) ~[tomcat-embed-core-9.0.58.jar!/:na]


	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4613) ~[tomcat-embed-core-9.0.58.jar!/:na]


	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5256) ~[tomcat-embed-core-9.0.58.jar!/:na]


	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.58.jar!/:na]


	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396) ~[tomcat-embed-core-9.0.58.jar!/:na]


	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386) ~[tomcat-embed-core-9.0.58.jar!/:na]


	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]


	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-embed-core-9.0.58.jar!/:na]


	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140) ~[na:na]


	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919) ~[tomcat-embed-core-9.0.58.jar!/:na]


	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835) ~[tomcat-embed-core-9.0.58.jar!/:na]


	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.58.jar!/:na]


	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396) ~[tomcat-embed-core-9.0.58.jar!/:na]


	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386) ~[tomcat-embed-core-9.0.58.jar!/:na]


	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]


	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-embed-core-9.0.58.jar!/:na]


	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140) ~[na:na]


	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919) ~[tomcat-embed-core-9.0.58.jar!/:na]


	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263) ~[tomcat-embed-core-9.0.58.jar!/:na]


	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.58.jar!/:na]


	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432) ~[tomcat-embed-core-9.0.58.jar!/:na]


	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.58.jar!/:na]


	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927) ~[tomcat-embed-core-9.0.58.jar!/:na]


	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.58.jar!/:na]


	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:486) ~[tomcat-embed-core-9.0.58.jar!/:na]


	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:123) ~[spring-boot-2.6.4.jar!/:2.6.4]


	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:104) ~[spring-boot-2.6.4.jar!/:2.6.4]


	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:478) ~[spring-boot-2.6.4.jar!/:2.6.4]


	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:211) ~[spring-boot-2.6.4.jar!/:2.6.4]


	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:182) ~[spring-boot-2.6.4.jar!/:2.6.4]


	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:160) ~[spring-boot-2.6.4.jar!/:2.6.4]


	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:577) ~[spring-context-5.3.16.jar!/:5.3.16]


	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.4.jar!/:2.6.4]


	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) ~[eureka-0.0.1-SNAPSHOT-aot.jar!/:na]


	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) ~[eureka-0.0.1-SNAPSHOT-aot.jar!/:na]


	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[eureka-0.0.1-SNAPSHOT-aot.jar!/:na]


	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[eureka-0.0.1-SNAPSHOT-aot.jar!/:na]


	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[eureka-0.0.1-SNAPSHOT-aot.jar!/:na]


	at com.garpix.eureka.EurekaApplicationKt.main(EurekaApplication.kt:15) ~[classes!/:na]


	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]


	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]


	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]


	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]


	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[application.jar:na]


	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[application.jar:na]


	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[application.jar:na]


	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[application.jar:na]



2022-03-23 12:59:10.979 ERROR 1 --- [           main] o.apache.catalina.core.StandardContext   : One or more Filters failed to start. Full details will be found in the appropriate container log file


2022-03-23 12:59:10.980 ERROR 1 --- [           main] o.apache.catalina.core.StandardContext   : Context [] startup failed due to previous errors


2022-03-23 12:59:11.045  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]


2022-03-23 12:59:11.055  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat


2022-03-23 12:59:11.078  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 



Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.


2022-03-23 12:59:11.111 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed



org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat


	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:163) ~[spring-boot-2.6.4.jar!/:2.6.4]


	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:577) ~[spring-context-5.3.16.jar!/:5.3.16]


	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.4.jar!/:2.6.4]


	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) ~[eureka-0.0.1-SNAPSHOT-aot.jar!/:na]


	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) ~[eureka-0.0.1-SNAPSHOT-aot.jar!/:na]


	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[eureka-0.0.1-SNAPSHOT-aot.jar!/:na]


	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[eureka-0.0.1-SNAPSHOT-aot.jar!/:na]


	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[eureka-0.0.1-SNAPSHOT-aot.jar!/:na]


	at com.garpix.eureka.EurekaApplicationKt.main(EurekaApplication.kt:15) ~[classes!/:na]


	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]


	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]


	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]


	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]


	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[application.jar:na]


	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[application.jar:na]


	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[application.jar:na]


	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[application.jar:na]


Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat


	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:142) ~[spring-boot-2.6.4.jar!/:2.6.4]


	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:104) ~[spring-boot-2.6.4.jar!/:2.6.4]


	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:478) ~[spring-boot-2.6.4.jar!/:2.6.4]


	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:211) ~[spring-boot-2.6.4.jar!/:2.6.4]


	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:182) ~[spring-boot-2.6.4.jar!/:2.6.4]


	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:160) ~[spring-boot-2.6.4.jar!/:2.6.4]


	... 16 common frames omitted


Caused by: java.lang.IllegalStateException: StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[] failed to start


	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.rethrowDeferredStartupExceptions(TomcatWebServer.java:187) ~[spring-boot-2.6.4.jar!/:2.6.4]


	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:126) ~[spring-boot-2.6.4.jar!/:2.6.4]


	... 21 common frames omitted

```

**Comment by archsia** [comment]
It's default build.gradle from spring.initializer. I'm deleted `experimental.aot` dependency and server start working.
