### ISSUE TITLE
2.x Eureka Read - Exception handling in DNS loading

### ISSUE THREAD

**Issue by qiangdavidliu** [Netflix/eureka#448]
ResourceLoaderException thrown in DnsChangeNotificationSource.java does not seem to be handled by callers, and have observed to be thrown on the read server:

<pre>
Exception in thread "RxComputationThreadPool-4" java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: com.netflix.eureka2.utils.rx.ResourceObservable$ResourceLoaderException: DNS failure on subsequent access
	at com.netflix.eureka2.interests.host.DnsChangeNotificationSource$DnsResolverTask.reload(DnsChangeNotificationSource.java:100)
	at com.netflix.eureka2.utils.rx.ResourceObservable$ResourceLoaderExecutor.call(ResourceObservable.java:219)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
	... 7 more
Caused by: javax.naming.CommunicationException: DNS error [Root exception is java.net.SocketTimeoutException: Receive timed out]; remaining name 'some.record.name'
	at com.sun.jndi.dns.DnsClient.query(DnsClient.java:300)
	at com.sun.jndi.dns.Resolver.query(Resolver.java:81)
	at com.sun.jndi.dns.DnsContext.c_getAttributes(DnsContext.java:430)
	at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_getAttributes(ComponentDirContext.java:231)
	at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.getAttributes(PartialCompositeDirContext.java:139)
	at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.getAttributes(PartialCompositeDirContext.java:127)
	at javax.naming.directory.InitialDirContext.getAttributes(InitialDirContext.java:142)
	at com.netflix.eureka2.interests.host.DnsChangeNotificationSource$DnsResolverTask.resolveName(DnsChangeNotificationSource.java:135)
	at com.netflix.eureka2.interests.host.DnsChangeNotificationSource$DnsResolverTask.resolveServerDN(DnsChangeNotificationSource.java:123)
	at com.netflix.eureka2.interests.host.DnsChangeNotificationSource$DnsResolverTask.reload(DnsChangeNotificationSource.java:95)
	... 9 more
Caused by: java.net.SocketTimeoutException: Receive timed out
	at java.net.PlainDatagramSocketImpl.peekData(Native Method)
	at java.net.DatagramSocket.receive(DatagramSocket.java:767)
	at com.sun.jndi.dns.DnsClient.doUdpQuery(DnsClient.java:411)
	at com.sun.jndi.dns.DnsClient.query(DnsClient.java:203)
	... 18 more
</pre>

**Comment by qiangdavidliu** [comment]
fixed
