### ISSUE TITLE
DiscoveryClient fails to unregister servo monitors from JmxMonitorRegistry

### ISSUE THREAD

**Issue by spencergibb** [Netflix/eureka#704]
Similar to #638 which was for EurekaServer. Using eureka 1.3.4.

```
javax.management.InstanceNotFoundException: com.netflix.servo:name=eurekaClient.resolver.lastLoadTimestamp,class=AsyncResolver,id=bootstrap,level=INFO,type=GAUGE
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095) ~[na:1.8.0_05]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.exclusiveUnregisterMBean(DefaultMBeanServerInterceptor.java:427) ~[na:1.8.0_05]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.unregisterMBean(DefaultMBeanServerInterceptor.java:415) ~[na:1.8.0_05]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.unregisterMBean(JmxMBeanServer.java:546) ~[na:1.8.0_05]
	at com.netflix.servo.jmx.JmxMonitorRegistry.unregister(JmxMonitorRegistry.java:125) ~[servo-core-0.10.0.jar:0.10.0]
	at com.netflix.servo.DefaultMonitorRegistry.unregister(DefaultMonitorRegistry.java:143) [servo-core-0.10.0.jar:0.10.0]
	at com.netflix.servo.monitor.Monitors.unregisterObject(Monitors.java:197) [servo-core-0.10.0.jar:0.10.0]
	at com.netflix.discovery.shared.resolver.AsyncResolver.shutdown(AsyncResolver.java:136) [eureka-client-1.3.4.jar:1.3.4]
	at com.netflix.discovery.DiscoveryClient$EurekaTransport.shutdown(DiscoveryClient.java:259) [eureka-client-1.3.4.jar:1.3.4]
	at com.netflix.discovery.DiscoveryClient.shutdown(DiscoveryClient.java:962) [eureka-client-1.3.4.jar:1.3.4]
	at org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration.onApplicationEvent(EurekaDiscoveryClientConfiguration.java:189) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:227) [spring-context-4.2.3.BUILD-20151109.174732-45.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:144) [spring-context-4.2.3.BUILD-20151109.174732-45.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:106) [spring-context-4.2.3.BUILD-20151109.174732-45.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163) [spring-context-4.2.3.BUILD-20151109.174732-45.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136) [spring-context-4.2.3.BUILD-20151109.174732-45.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:380) [spring-context-4.2.3.BUILD-20151109.174732-45.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334) [spring-context-4.2.3.BUILD-20151109.174732-45.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:961) [spring-context-4.2.3.BUILD-20151109.174732-45.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:928) [spring-context-4.2.3.BUILD-20151109.174732-45.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.boot.builder.ParentContextCloserApplicationListener$ContextCloserListener.onApplicationEvent(ParentContextCloserApplicationListener.java:102) [spring-boot-1.3.0.BUILD-20151110.135218-784.jar:1.3.0.BUILD-SNAPSHOT]
	at org.springframework.boot.builder.ParentContextCloserApplicationListener$ContextCloserListener.onApplicationEvent(ParentContextCloserApplicationListener.java:86) [spring-boot-1.3.0.BUILD-20151110.135218-784.jar:1.3.0.BUILD-SNAPSHOT]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163) [spring-context-4.2.3.BUILD-20151109.174732-45.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136) [spring-context-4.2.3.BUILD-20151109.174732-45.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:380) [spring-context-4.2.3.BUILD-20151109.174732-45.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334) [spring-context-4.2.3.BUILD-20151109.174732-45.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:961) [spring-context-4.2.3.BUILD-20151109.174732-45.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:895) [spring-context-4.2.3.BUILD-20151109.174732-45.jar:4.2.3.BUILD-SNAPSHOT]
```

**Comment by tbak** [comment]
@spencergibb I have tried to reproduce this error with no success. I have seen servo ignores these kinds of errors internally (https://github.com/Netflix/servo/commit/0636b23a60889341a5c1d0dc8a1adc5b0c830180). Can you confirm?

**Comment by Yannic92** [comment]
@tbak I can confirm this issue. I will try to provide a short example in the next days.

**Comment by spencergibb** [comment]
@tbak We're still on servo 0.10.0

**Comment by cforce** [comment]
Same issue here with Brixton. M4

**Comment by qiangdavidliu** [comment]
Eureka has been updated to servo 0.10.x
