### ISSUE TITLE
Unable to run eureka server on Weblogic 12c

### ISSUE THREAD

**Issue by omkar9999** [Netflix/eureka#719]
i'm unable to run eureka server on Weblogic 12c.
war file is deployed successfully on Weblogic 12c but I'm receiving following error in server logs:

[2015-12-10T13:36:46.135+05:30] [AdminServer] [ERROR] [] [com.netflix.eureka.PeerAwareInstanceRegistry] [tid: Eureka-EvictionTimer] [userId: <anonymous>] [ecid: 4c164384-726a-4c35-a306-2cb86fb2103a-00000003,0:8] [APP: eureka-server-1.1.37] The lease expiration has been disabled since the number of renewals per minute   is lower than the minimum threshold. Number of Renewals Last Minute : 0. The Threshold is 0.85 of total instances : 0
[2015-12-10T13:37:08.337+05:30] [AdminServer] [ERROR] [] [com.netflix.discovery.DiscoveryClient] [tid: DiscoveryClient_ServiceURLUpdater] [userId: <anonymous>] [ecid: 4c164384-726a-4c35-a306-2cb86fb2103a-00000003,0:9] [APP: eureka-server-1.1.37] DISCOVERY: invalid zone - defaultZone defaulting to defaultZone
[2015-12-10T13:37:11.702+05:30] [AdminServer] [WARNING] [] [com.netflix.discovery.DiscoveryClient] [tid: DiscoveryClient_CacheRefresher] [userId: <anonymous>] [ecid: 4c164384-726a-4c35-a306-2cb86fb2103a-00000003,0:6] [APP: eureka-server-1.1.37] Action: Refresh  => returned status of 404 from http://localhost/eureka/v2/apps/
[2015-12-10T13:37:11.704+05:30] [AdminServer] [ERROR] [] [com.netflix.discovery.DiscoveryClient] [tid: DiscoveryClient_CacheRefresher] [userId: <anonymous>] [ecid: 4c164384-726a-4c35-a306-2cb86fb2103a-00000003,0:6] [APP: eureka-server-1.1.37] Can't get a response from http://localhost/eureka/v2/apps/[[
Can't contact any eureka nodes - possibly a security group issue? java.lang.RuntimeException: Bad status: 404
	at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:833)
	at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:753)
	at com.netflix.discovery.DiscoveryClient.getAndStoreFullRegistry(DiscoveryClient.java:615)
	at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:562)
	at com.netflix.discovery.DiscoveryClient.access$1200(DiscoveryClient.java:87)
	at com.netflix.discovery.DiscoveryClient$CacheRefreshThread.run(DiscoveryClient.java:1316)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

]]
[2015-12-10T13:37:11.704+05:30] [AdminServer] [ERROR] [] [com.netflix.discovery.DiscoveryClient] [tid: DiscoveryClient_CacheRefresher] [userId: <anonymous>] [ecid: 4c164384-726a-4c35-a306-2cb86fb2103a-00000003,0:6] [APP: eureka-server-1.1.37] DiscoveryClient_EUREKA/MACHINE_NAME - was unable to refresh it's cache! status = Bad status: 404[[
java.lang.RuntimeException: Bad status: 404
	at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:833)
	at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:753)
	at com.netflix.discovery.DiscoveryClient.getAndStoreFullRegistry(DiscoveryClient.java:615)
	at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:562)
	at com.netflix.discovery.DiscoveryClient.access$1200(DiscoveryClient.java:87)
	at com.netflix.discovery.DiscoveryClient$CacheRefreshThread.run(DiscoveryClient.java:1316)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

]]

NOTE: MACHINE_NAME is a name of my windows machine which cannot be disclosed

**Comment by tbak** [comment]
You Eureka client/server configuration assumes that you run server on port
80, and that the context path is 'eureka' (http://localhost/eureka/v2/apps).
You are using probably default configuration hence localhost address is
used, not routable address of the host. Please consult
https://github.com/Netflix/eureka/tree/master/eureka-examples/conf for
example configuration. You need to change 'eureka.serviceUrl.default' to
your eureka deployment URL.
/Tomasz

**Comment by tbak** [comment]
I am closing this issue. Please, reopen it if you wish to continue this discussion.
