### ISSUE TITLE
Document version compatibility

### ISSUE THREAD

**Issue by sfussenegger** [Netflix/eureka#735]
I believe this one should be document as I wasn't able to find anything in the wiki.

There are three main questions that come to mind:

1) what do different version increments represent?
2) is it supported to run clients with earlier versions than the server? patch level or minor too?
3) is it supported to run servers with different versions (e.g. while upgrading a cluster)? patch level or minor?

**Comment by qiangdavidliu** [comment]
@sfussenegger thanks, we will update the wiki. To address your 3 specific questions:

1) client/server protocol compatibility should be ensured for minor version updates. Minor version bumps may indicate client side java API changes or dependency changes but should not impact client/server protocol.
2) server should be compatible with earlier clients at minor version differences.
3) servers are designed to be upgraded one at a time (but preferably not between versions that are too far apart) so there is server-side compatibility between minor version differences.

**Comment by sfussenegger** [comment]
@qiangdavidliu thanks for pointing this out. Just to clarify things a little further: we are talking `[major].[minor].[patch]` (as in [semver](http://semver.org/)), right? So client-server protocol has been backward-compatible for the whole `1.x` releases? Therefore `1.1.147` clients (currently the latest used by spring-cloud-netflix) should be compatible with the currently latest server (that is `1.3.7`), correct?

**Comment by qiangdavidliu** [comment]
@sfussenegger yes, we use semantic versioning for eureka. Id like to say we've been trying out best to keep complete protocol compatibility for the 1.x series of releases, though to be honest I haven't really validated some of the truly early versions (say from 3+ years ago). I can however confirm that 1.1.147 is compatible with server version 1.3.7 (we have instances of 1.1.147 running with our current server deployments of 1.3.7).

One caveat is that we don't package internally using spring-cloud-netflix, so I can't verify any compatibility requirements w.r.t. the spring wrappings.

**Comment by spencergibb** [comment]
In Brixton snapshots spring-cloud-netflix has upgraded to 1.3.7.

**Comment by qiangdavidliu** [comment]
Thanks for the update @spencergibb .
@sfussenegger I'm going to close this issue for now. Please feel free to re-open if you have further questions.

**Comment by kristofferpeterhansel** [comment]
So spring-cloud-netflix Brixton RC1 is now using Eureka 1.4.4 and I am seeing some issues with connecting to the 1.1.x-bases Eureka server (from a previous spring-cloud-netflix version)  we currently use. Is this supposed to be compatible?

**Comment by spencergibb** [comment]
What issues? It may be a spring Cloud issue, not eureka.

**Comment by kristofferpeterhansel** [comment]
Well. That was why I started asking in https://github.com/spring-cloud/spring-cloud-netflix/issues/953 . Since I am getting issues very similar to that.

Basically the service registers fine. But updates fail with exceptions like this:
```
2016-04-13 15:06:13.289 ERROR 46782 --- [tbeatExecutor-0] c.n.d.s.t.d.RedirectingEurekaHttpClient  : Request execution error

javax.ws.rs.WebApplicationException: null
	at com.netflix.discovery.provider.DiscoveryJerseyProvider.readFrom(DiscoveryJerseyProvider.java:110) ~[eureka-client-1.4.4.jar:1.4.4]
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:634) ~[jersey-client-1.19.1.jar:1.19.1]
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:586) ~[jersey-client-1.19.1.jar:1.19.1]
	at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.sendHeartBeat(AbstractJerseyEurekaHttpClient.java:105) ~[eureka-client-1.4.4.jar:1.4.4]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92) [eureka-client-1.4.4.jar:1.4.4]
	at com.netflix.discovery.shared.transport.decorator.MetricsCollectingEurekaHttpClient.execute(MetricsCollectingEurekaHttpClient.java:73) ~[eureka-client-1.4.4.jar:1.4.4]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) [eureka-client-1.4.4.jar:1.4.4]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92) [eureka-client-1.4.4.jar:1.4.4]
	at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.execute(RedirectingEurekaHttpClient.java:89) ~[eureka-client-1.4.4.jar:1.4.4]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) [eureka-client-1.4.4.jar:1.4.4]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92) [eureka-client-1.4.4.jar:1.4.4]
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:119) [eureka-client-1.4.4.jar:1.4.4]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) [eureka-client-1.4.4.jar:1.4.4]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92) [eureka-client-1.4.4.jar:1.4.4]
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77) [eureka-client-1.4.4.jar:1.4.4]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) [eureka-client-1.4.4.jar:1.4.4]
	at com.netflix.discovery.DiscoveryClient.renew(DiscoveryClient.java:823) [eureka-client-1.4.4.jar:1.4.4]
	at com.netflix.discovery.DiscoveryClient$HeartbeatThread.run(DiscoveryClient.java:1379) [eureka-client-1.4.4.jar:1.4.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_73]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_73]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_73]
```

**Comment by qiangdavidliu** [comment]
@kristofferpeterhansel it's possible you are running into an eureka incompatibility also. We keep a much closer eye on (earlier) client, (later) server compatibility than the reverse (looks like you are trying to run client 1.4.4 with server 1.1.x?), and typically upgrade the server much more aggressively than the client versions.

**Comment by kristofferpeterhansel** [comment]
@qiangdavidliu You are correct. It is exactly the scenario you describe. We run a spring-cloud-netflix 1.0.1-based Eureka server. Making it 1.1.147.

I suppose there is technically no reason why we couldn't upgrade it - since it is only a Eureka server and have no other dependencies. But it is a bit of a problem if we have to kill all our Eureka instances at the same time to do it. And I suspect they would have the same problem and can't replicate data between an old and a new instance?

**Comment by qiangdavidliu** [comment]
@kristofferpeterhansel how big of a cluster do you run? You *should* be able to upgrade the nodes one by one ... but given that the version 1.1.147 is now over a year old, it's "possible" an incompatibility exist. What happens if you just upgrade one of the nodes to the latest server build? Does it work for you?

**Comment by kristofferpeterhansel** [comment]
@qiangdavidliu Currently we run just two instances in each of our environments. There is no reason why I couldn't try it out in our test environment and see what happens. So I suppose I'll try that out when I

I realise it is an old version. But since we are using the version that comes with Spring Cloud Netflix. That is sort of impose on us by that. But I guess that is mainly a problem with that project not getting all that often updates. And a good reason to reconsider why we are using the Eureka server wrapped in Spring Boot.

**Comment by sfussenegger** [comment]
@kristofferpeterhansel we ended up using "plain" eureka server for the same reason. the spring-cloud version really doesn't add anything other than a nice launcher inside IDEs. Eureka documentation is scarce already and the spring-cloud version really doesn't help. 

It's pretty much what Samsung does to Android. Changes are mostly a matter of taste, come with their own issues and you wait forever for updates ;)

**Comment by qiangdavidliu** [comment]
Closing this issue as the discussion seem to have to come to some conclusion.
