### ISSUE TITLE
"Cannot execute request on any known server" when i set up a Eureka cluster by skyDns(2)

### ISSUE THREAD

**Issue by fangzhining** [Netflix/eureka#780]
After reading the solution of 
 "Cannot execute request on any known server" when i set up a Eureka cluster by skyDns #777, i have  changed "http://10.120.180.117:8080/discovery/v2/" into "http://10.120.180.117:8080/eureka/v2/",but it does not work,i can't setup the cluster of eureka.

The Error log almost is the same.It can only find one txtRecord.

2016-04-18 20:33:20,733 INFO com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver:40 [localhost-startStop-1] [getClusterEndpoints] Resolving eureka endpoints via DNS
The txtRecord is : us-east-1d.bar.skydns.paas
The cnamesString is : [us-east-1d.bar.skydns.paas]
The rootClusterDNS is : txt.us-east-1.bar.skydns.paas
The zoneDomain is : us-east-1d.bar.skydns.paas
The txtRecord is : http://10.120.180.117:8080/eureka/v2/
The cnamesString is : [http://10.120.180.117:8080/eureka/v2/]
The txtRecord is : http://10.120.180.117:8080/eureka/v2/
The cnamesString is : [http://10.120.180.117:8080/eureka/v2/]
The zoneAddresses is : http://10.120.180.117:8080/eureka/v2/
2016-04-18 20:33:20,807 INFO com.netflix.discovery.DiscoveryClient:920 [localhost-startStop-1] [fetchRegistry] Disable delta property : false
2016-04-18 20:33:20,807 INFO com.netflix.discovery.DiscoveryClient:921 [localhost-startStop-1] [fetchRegistry] Single vip registry refresh property : null
2016-04-18 20:33:20,807 INFO com.netflix.discovery.DiscoveryClient:922 [localhost-startStop-1] [fetchRegistry] Force full registry fetch : false
2016-04-18 20:33:20,807 INFO com.netflix.discovery.DiscoveryClient:923 [localhost-startStop-1] [fetchRegistry] Application is null : false
2016-04-18 20:33:20,807 INFO com.netflix.discovery.DiscoveryClient:924 [localhost-startStop-1] [fetchRegistry] Registered Applications size is zero : true
2016-04-18 20:33:20,808 INFO com.netflix.discovery.DiscoveryClient:926 [localhost-startStop-1] [fetchRegistry] Application version is -1: true
2016-04-18 20:33:20,808 INFO com.netflix.discovery.DiscoveryClient:1009 [localhost-startStop-1] [getAndStoreFullRegistry] Getting all instance registry info from the eureka server
2016-04-18 20:33:20,899 ERROR com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient:83 [localhost-startStop-1] [execute] Request execution error
com.sun.jersey.api.client.ClientHandlerException: java.net.UnknownHostException: http: unknown error
at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187)
at com.sun.jersey.api.client.filter.GZIPContentEncodingFilter.handle(GZIPContentEncodingFilter.java:123)
at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27)
at com.sun.jersey.api.client.Client.handle(Client.java:652)
at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:509)
at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.getApplicationsInternal(AbstractJerseyEurekaHttpClient.java:194)
at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.getApplications(AbstractJerseyEurekaHttpClient.java:165)
at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
at com.netflix.discovery.shared.transport.decorator.MetricsCollectingEurekaHttpClient.execute(MetricsCollectingEurekaHttpClient.java:73)
at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.executeOnNewServer(RedirectingEurekaHttpClient.java:118)
at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.execute(RedirectingEurekaHttpClient.java:79)
at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:119)
at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
at com.netflix.discovery.DiscoveryClient.getAndStoreFullRegistry(DiscoveryClient.java:1013)
at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:927)
at com.netflix.discovery.DiscoveryClient.(DiscoveryClient.java:441)
at com.netflix.discovery.DiscoveryClient.(DiscoveryClient.java:304)
at com.netflix.discovery.DiscoveryClient.(DiscoveryClient.java:300)
at com.netflix.eureka.EurekaBootStrap.initEurekaServerContext(EurekaBootStrap.java:147)
at com.netflix.eureka.EurekaBootStrap.contextInitialized(EurekaBootStrap.java:96)
at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:939)
at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1812)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.UnknownHostException: http: unknown error
at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
at java.net.InetAddress.getAllByName(InetAddress.java:1192)
at java.net.InetAddress.getAllByName(InetAddress.java:1126)
at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:44)
at org.apache.http.impl.conn.DefaultClientConnectionOperator.resolveHostname(DefaultClientConnectionOperator.java:259)
at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:159)
at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:115)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:173)
... 41 more
2016-04-18 20:33:20,902 WARN com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient:129 [localhost-startStop-1] [execute] Request execution failure
2016-04-18 20:33:20,903 ERROR com.netflix.discovery.DiscoveryClient:934 [localhost-startStop-1] [fetchRegistry] DiscoveryClient_EUREKA/SZV1000048538 - was unable to refresh its cache! status = Cannot execute request on any known server
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:111)
at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
at com.netflix.discovery.DiscoveryClient.getAndStoreFullRegistry(DiscoveryClient.java:1013)
at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:927)
at com.netflix.discovery.DiscoveryClient.(DiscoveryClient.java:441)
at com.netflix.discovery.DiscoveryClient.(DiscoveryClient.java:304)
at com.netflix.discovery.DiscoveryClient.(DiscoveryClient.java:300)
at com.netflix.eureka.EurekaBootStrap.initEurekaServerContext(EurekaBootStrap.java:147)
at com.netflix.eureka.EurekaBootStrap.contextInitialized(EurekaBootStrap.java:96)
at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:939)
at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1812)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

**Comment by qiangdavidliu** [comment]
@fangzhining sorry about that, looks like when I fixed the documentation mistake on that page, I did not do it fully (update yet again). For the dns option, you only need the hostname in the records, and should not include "http://", the port, nor the "eureka/v2".

**Comment by fangzhining** [comment]
@qiangdavidliu ,thank you for you solution,but i hava done this too,the following are my attempts;
The first trying:
The metadata in DNS:
dig txt.us-east-1.bar.skydns.paas txt
;; QUESTION SECTION:
;txt.us-east-1.bar.skydns.paas.	IN	TXT
;; ANSWER SECTION:
txt.us-east-1.bar.skydns.paas. 3600 IN	TXT	"us-east-1d.bar.skydns.paas"
txt.us-east-1.bar.skydns.paas. 3600 IN	TXT	"us-east-1c.bar.skydns.paas"

dig txt.us-east-1c.bar.skydns.paas txt
;; QUESTION SECTION:
;txt.us-east-1c.bar.skydns.paas.	IN	TXT
;; ANSWER SECTION:
txt.us-east-1c.bar.skydns.paas.	3600 IN	TXT	"10.120.180.235"

dig txt.us-east-1d.bar.skydns.paas txt
;; QUESTION SECTION:
;txt.us-east-1d.bar.skydns.paas.	IN	TXT
;; ANSWER SECTION:
txt.us-east-1d.bar.skydns.paas.	3600 IN	TXT	"10.120.180.117"

The result:
It can only get  one eureka endpoints via DNS,and at last 
2016-04-19 09:44:17,986 WARN  com.netflix.config.util.ConfigurationUtils:177 [localhost-startStop-1] [getConfigFromPropertiesFile] file:/usr/local/apache-tomcat-8.0.32/webapps/eureka/WEB-INF/classes/eureka-client.properties is already loaded
2016-04-19 09:44:18,334 INFO  com.netflix.discovery.provider.DiscoveryJerseyProvider:70 [localhost-startStop-1] [<init>] Using JSON encoding codec LegacyJacksonJson
2016-04-19 09:44:18,335 INFO  com.netflix.discovery.provider.DiscoveryJerseyProvider:71 [localhost-startStop-1] [<init>] Using JSON decoding codec LegacyJacksonJson
2016-04-19 09:44:18,335 INFO  com.netflix.discovery.provider.DiscoveryJerseyProvider:80 [localhost-startStop-1] [<init>] Using XML encoding codec XStreamXml
2016-04-19 09:44:18,335 INFO  com.netflix.discovery.provider.DiscoveryJerseyProvider:81 [localhost-startStop-1] [<init>] Using XML decoding codec XStreamXml
2016-04-19 09:44:18,600 INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver:40 [localhost-startStop-1] [getClusterEndpoints] Resolving eureka endpoints via DNS
The txtRecord is : us-east-1c.bar.skydns.paas
The cnamesString is : [us-east-1c.bar.skydns.paas]
The rootClusterDNS is : txt.us-east-1.bar.skydns.paas
The zoneDomain is : us-east-1c.bar.skydns.paas
The txtRecord is : 10.120.180.235
The cnamesString is : [10.120.180.235]
The txtRecord is : 10.120.180.235
The cnamesString is : [10.120.180.235]
The zoneAddresses is : 10.120.180.235
2016-04-19 09:44:18,646 INFO  com.netflix.discovery.DiscoveryClient:920 [localhost-startStop-1] [fetchRegistry] Disable delta property : false
2016-04-19 09:44:18,646 INFO  com.netflix.discovery.DiscoveryClient:921 [localhost-startStop-1] [fetchRegistry] Single vip registry refresh property : null
2016-04-19 09:44:18,646 INFO  com.netflix.discovery.DiscoveryClient:922 [localhost-startStop-1] [fetchRegistry] Force full registry fetch : false
2016-04-19 09:44:18,646 INFO  com.netflix.discovery.DiscoveryClient:923 [localhost-startStop-1] [fetchRegistry] Application is null : false
2016-04-19 09:44:18,647 INFO  com.netflix.discovery.DiscoveryClient:924 [localhost-startStop-1] [fetchRegistry] Registered Applications size is zero : true
2016-04-19 09:44:18,647 INFO  com.netflix.discovery.DiscoveryClient:926 [localhost-startStop-1] [fetchRegistry] Application version is -1: true
2016-04-19 09:44:18,647 INFO  com.netflix.discovery.DiscoveryClient:1009 [localhost-startStop-1] [getAndStoreFullRegistry] Getting all instance registry info from the eureka server

the response of "http://10.120.180.117:8080/eureka/"
DS Replicas: 10.120.180.235
Instances currently registered with Eureka
Application

Search Application
AMIs

Search AMIs
Availability Zones

Search Availability Zones
Status

Search Status
Application	AMIs	Availability Zones	Status
No data available in table
General Info
Name	Value
environment	prod
num-of-cpus	4
total-avail-memory	567mb
current-memory-usage	237mb (41%)
server-uptime	00:02
registered-replicas	http://10.120.180.235:8080/eureka/v2/
available-replicas	
unavailable-replicas	http://10.120.180.235:8080/eureka/v2/,
Instance Info
Name	Value
ipAddr	10.120.180.117
status	UP

The Third trying:
The metadata in DNS:
dig txt.us-east-1.bar.skydns.paas txt
;; QUESTION SECTION:
;txt.us-east-1.bar.skydns.paas.	IN	TXT
;; ANSWER SECTION:
txt.us-east-1.bar.skydns.paas. 3600 IN	TXT	"us-east-1c.bar.skydns.paas"

dig txt.us-east-1c.bar.skydns.paas txt
;; QUESTION SECTION:
;txt.us-east-1c.bar.skydns.paas.	IN	TXT
;; ANSWER SECTION:
txt.us-east-1c.bar.skydns.paas.	3600 IN	TXT	" 10.120.180.235 10.120.180.117 "

But the Domain Name Resolution is good, but there will get a extra endpoint ,like 
the response of "http://10.120.180.235:8080/eureka/"
 
DS Replicas:
Instances currently registered with Eureka
Application

Search Application
AMIs

Search AMIs
Availability Zones

Search Availability Zones
Status

Search Status
Application	AMIs	Availability Zones	Status
No data available in table
General Info
Name	Value
environment	prod
num-of-cpus	4
total-avail-memory	562mb
current-memory-usage	317mb (56%)
server-uptime	00:01
registered-replicas	http://"10.120.180.235:8080/eureka/v2/, http://10.120.180.117":8080/eureka/v2/
available-replicas	
unavailable-replicas	http://"10.120.180.235:8080/eureka/v2/,http://10.120.180.117":8080/eureka/v2/,
Instance Info
Name	Value
ipAddr	10.120.180.235
status	UP

2016-04-19 10:02:48,307 ERROR com.netflix.eureka.util.StatusUtil:72 [http-nio-8080-exec-6] [isReplicaAvailable] Could not determine if the replica is available
java.net.URISyntaxException: Illegal character in authority at index 7: http://10.120.180.117":8080/eureka/v2/


The Sencond trying:
The metadata in DNS:
dig txt.us-east-1.bar.skydns.paas txt
;; QUESTION SECTION:
;txt.us-east-1.bar.skydns.paas.	IN	TXT
;; ANSWER SECTION:
txt.us-east-1.bar.skydns.paas. 3600 IN	TXT	"us-east-1c.bar.skydns.paas"

dig txt.us-east-1c.bar.skydns.paas txt
;; QUESTION SECTION:
;txt.us-east-1c.bar.skydns.paas.	IN	TXT
;; ANSWER SECTION:
txt.us-east-1c.bar.skydns.paas.	3600 IN	TXT	"10.120.180.235 10.120.180.117"

But the Domain Name Resolution is wrong, there will be get a extra ",like 
the response of "http://10.120.180.235:8080/eureka/"

DS Replicas: 10.120.180.23510.120.180.117
Instances currently registered with Eureka
Application

Search Application
AMIs

Search AMIs
Availability Zones

Search Availability Zones
Status

Search Status
Application	AMIs	Availability Zones	Status
EUREKA	n/a (2),	(2),	UP (2) - SZV1000048497, SZV1000048537,
General Info
Name	Value
environment	prod
num-of-cpus	4
total-avail-memory	374mb
current-memory-usage	299mb (79%)
server-uptime	00:00
registered-replicas	http://10.120.180.235:8080/eureka/v2/, http://":8080/eureka/v2/, http://10.120.180.117:8080/eureka/v2/
available-replicas	
unavailable-replicas	http://10.120.180.235:8080/eureka/v2/,http://":8080/eureka/v2/,http://10.120.180.117:8080/eureka/v2/,
Instance Info
Name	Value
ipAddr	10.120.180.235
status	UP

Is this the cluster of eureka?    if yes,how could i rm the http://":8080/eureka/v2/ ?  
when i use the  cluster of eureka ,are there will be any problems?

**Comment by qiangdavidliu** [comment]
@fangzhining can you tell me which AwsBinder you are using? Are you using Route53 or EIP? Thanks.

**Comment by fangzhining** [comment]
@qiangdavidliu , i may have found what is wrong.i use skydns as my DNS,when i set the domain,it is not the format such as :
**txt.us-east-1.mydomaintest.netflix.net="us-east-1c.mydomaintest.netflix.net" 
"us-east-1d.mydomaintest.netflix.net" "us-east-1e.mydomaintest.netflix.net"**
but like this:
curl -XPUT http://127.0.0.1:4001/v2/keys/skydns/paas/skydns/bar/us-east-1/txt/x1 -d value='{"text":"us-east-1c.bar.skydns.paas","targetstrip":1}'
curl -XPUT http://127.0.0.1:4001/v2/keys/skydns/paas/skydns/bar/us-east-1/txt/x2 -d value='{"text":"us-east-1d.bar.skydns.paas","targetstrip":1}'

and the function of  **getCNamesFromTxtRecord in DnsResolver.java **,always only find the first one.

then in order to adapt to the format, i set domain in skydns like this ：
curl -XPUT http://127.0.0.1:4001/v2/keys/skydns/paas/skydns/bar/us-east-1/txt/x1 -d value='{"text":"us-east-1c.bar.skydns.paas us-east-1d.bar.skydns.paas","targetstrip":1}'

there will be another problem,when the function of  **getCNamesFromTxtRecord in DnsResolver.java **  run the code:**String[] cnames = txtRecord.split(" ");**.
the cnames  is ：["us-east-1d.bar.skydns.paas,us-east-1c.bar.skydns.paas"]. it is not right.


so, at last ,i change the function **getCNamesFromTxtRecord**,rm the " in the element of cnames  ,it seems to be all right the result is as the following:

the response of http://10.120.180.235:8080/eureka/

DS Replicas: 10.120.180.23510.120.180.11710.120.175.175
Instances currently registered with Eureka
Application

Search Application
AMIs

Search AMIs
Availability Zones

Search Availability Zones
Status

Search Status
Application	AMIs	Availability Zones	Status
EUREKA	n/a (3),	(3),	UP (3) - SZV1000048497, SZV1000048537, SZV1000048538,
SAMPLEREGISTERINGSERVICE	n/a (1),	(1),	UP (1) - SZV1000048389,
General Info
Name	Value
environment	prod
num-of-cpus	4
total-avail-memory	638mb
current-memory-usage	278mb (43%)
server-uptime	00:15
registered-replicas	http://10.120.180.235:8080/eureka/v2/, http://10.120.180.117:8080/eureka/v2/, http://10.120.175.175:8080/eureka/v2/
available-replicas	
unavailable-replicas	http://10.120.180.235:8080/eureka/v2/,http://10.120.180.117:8080/eureka/v2/,http://10.120.175.175:8080/eureka/v2/,
Instance Info
Name	Value
ipAddr	10.120.180.235
status	UP


the response of http://10.120.180.117:8080/eureka/
DS Replicas: 10.120.180.23510.120.180.11710.120.175.175
Instances currently registered with Eureka
Application

Search Application
AMIs

Search AMIs
Availability Zones

Search Availability Zones
Status

Search Status
Application	AMIs	Availability Zones	Status
EUREKA	n/a (3),	(3),	UP (3) - SZV1000048497, SZV1000048537, SZV1000048538,
SAMPLEREGISTERINGSERVICE	n/a (1),	(1),	UP (1) - SZV1000048389,
General Info
Name	Value
environment	prod
num-of-cpus	4
total-avail-memory	632mb
current-memory-usage	277mb (43%)
server-uptime	00:15
registered-replicas	http://10.120.180.235:8080/eureka/v2/, http://10.120.180.117:8080/eureka/v2/, http://10.120.175.175:8080/eureka/v2/
available-replicas	
unavailable-replicas	http://10.120.180.235:8080/eureka/v2/,http://10.120.180.117:8080/eureka/v2/,http://10.120.175.175:8080/eureka/v2/,
Instance Info
Name	Value
ipAddr	10.120.180.117
status	UP

**Comment by tewner** [comment]
I'm having this same issue while using ActiveDirectory as my DNS server:

```
2017-12-21 17:43:45.457  WARN 3136 --- [nfoReplicator-0] c.n.d.s.t.d.RetryableEurekaHttpClient    : Request execution failed with message: Illegal character in authority at index 7: http://eureka02.mydomain.com":8761
2017-12-21 17:43:45.458  WARN 3136 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_UNKNOWN/eureka02.mydomain.com:8761 - registration failed Cannot execute request on any known server
```

Notice the quote appended to URL
Is this just something which works in Route53 and not on other DNS servers?

```
[eureka02 eureka]# dig txt.office-1a.eureka.mydomain.com TXT
; <<>> DiG 9.9.4-RedHat-9.9.4-51.el7 <<>> txt.office-1a.eureka.mydomain.com TXT
;; QUESTION SECTION:
;txt.office-1a.eureka.mydomain.com. IN TXT

;; ANSWER SECTION:
txt.office-1a.eureka.scene53il.com. 38400 IN TXT "eureka01.mydomain.com eureka02.mydomain.com"
```

**Comment by wangwenyao** [comment]
I’m having this same issue, when fix it?
The problem is in DnsResolver.getCNamesFromTxtRecord(), ` String txtRecord = null;
        if (attr != null) {
            txtRecord = attr.get().toString();
        }

        Set<String> cnamesSet = new TreeSet<String>();
        if (txtRecord == null || txtRecord.trim().isEmpty()) {
            return cnamesSet;
        }
        String[] cnames = txtRecord.split(" ");`
 here
       `txtRecord = attr.get().toString();`
