### ISSUE TITLE
Eureka Peer Server throwing java.lang.NullPointerException: null at com.netflix.eureka.registry.AbstractInstanceRegistry.renew

### ISSUE THREAD

**Issue by codependent** [Netflix/eureka#803]
I am using Spring Cloud Netflix to run two Eureka (1.4.6) servers with peer awareness and found this issue after their last API upgrade:

```
java.lang.NullPointerException: null
    at com.netflix.eureka.registry.AbstractInstanceRegistry.renew(AbstractInstanceRegistry.java:379) ~[eureka-core-1.4.6.jar:1.4.6]
    at com.netflix.eureka.registry.PeerAwareInstanceRegistryImpl.renew(PeerAwareInstanceRegistryImpl.java:401) ~[eureka-core-1.4.6.jar:1.4.6]
    at org.springframework.cloud.netflix.eureka.server.InstanceRegistry.renew(InstanceRegistry.java:127) ~[spring-cloud-netflix-eureka-server-1.1.0.RELEASE.jar:1.1.0.RELEASE]
    at com.netflix.eureka.resources.InstanceResource.renewLease(InstanceResource.java:112) ~[eureka-core-1.4.6.jar:1.4.6]
    at com.netflix.eureka.resources.PeerReplicationResource.handleHeartbeat(PeerReplicationResource.java:148) ~[eureka-core-1.4.6.jar:1.4.6]
    at com.netflix.eureka.resources.PeerReplicationResource.dispatch(PeerReplicationResource.java:113) ~[eureka-core-1.4.6.jar:1.4.6]
    at com.netflix.eureka.resources.PeerReplicationResource.batchReplication(PeerReplicationResource.java:85) ~[eureka-core-1.4.6.jar:1.4.6]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_74]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_74]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_74]
```

[Here are the details](https://github.com/spring-cloud/spring-cloud-netflix/issues/1065) to reproduce the problem.

**Comment by spencergibb** [comment]
I sent him here as the NPE is in pure eureka code

**Comment by qiangdavidliu** [comment]
Thanks @spencergibb. Looking at the the issue on the spring cloud netflix issue and the code, I see that the NPE is due to an out of order creation of a metrics counter. This is a harmless NPE that should only happen at init time. We will take a look at a simple PR to address this regardless.

The details: this is caused due to the second server not completing initialization (specifically, the openForTraffic() method on the local registry that creates the metrics counter in question) before having the first server heartbeat to the second server, and trying to log the renew metrics on an as yet non-existent metrics counter.

**Comment by qiangdavidliu** [comment]
Fix will be available in the next release.
