### ISSUE TITLE
com.netflix.eureka.shouldSSLConnectionsUseSystemSocketFactory not working

### ISSUE THREAD

**Issue by bitsofinfo** [Netflix/eureka#812]
on 1.4.8

When this `DiscoveryClient` constructor is invoked

`public DiscoveryClient(ApplicationInfoManager applicationInfoManager, final EurekaClientConfig config, DiscoveryClientOptionalArgs args) {`

The system property `com.netflix.eureka.shouldSSLConnectionsUseSystemSocketFactory=true` does not seem to be obeyed.

Trying to solve this kind of exception:

```
2016-07-05 18:53:58.676  INFO 655 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_MYAPP/hosa222:myapp-config:8888: registering service...
2016-07-05 18:53:58.683 ERROR 655 --- [nfoReplicator-0] c.n.d.s.t.d.RedirectingEurekaHttpClient  : Request execution error

com.sun.jersey.api.client.ClientHandlerException: javax.net.ssl.SSLException: Certificate for <localhost> doesn't match common name of the certificate subject: my-ssl-test
        at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187) ~[jersey-apache-client4-1.19.1.jar:1.19.1]
        at com.sun.jersey.api.client.filter.GZIPContentEncodingFilter.handle(GZIPContentEncodingFilter.java:123) ~[jersey-client-1.19.1.jar:1.19.1]
        at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27) ~[eureka-client-1.4.8.jar:1.4.8]
        at com.sun.jersey.api.client.Client.handle(Client.java:652) ~[jersey-client-1.19.1.jar:1.19.1]
        at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682) ~[jersey-client-1.19.1.jar:1.19.1]
        at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74) ~[jersey-client-1.19.1.jar:1.19.1]
        at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:570) ~[jersey-client-1.19.1.jar:1.19.1]
        at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.register(AbstractJerseyEurekaHttpClient.java:56) ~[eureka-client-1.4.8.jar:1.4.8]
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59) [eureka-client-1.4.8.jar:1.4.8]
        at com.netflix.discovery.shared.transport.decorator.MetricsCollectingEurekaHttpClient.execute(MetricsCollectingEurekaHttpClient.java:73) ~[eureka-client-1.4.8.jar:
```

**Comment by qiangdavidliu** [comment]
@bitsofinfo thanks. PR #813 should be a fix.

**Comment by bitsofinfo** [comment]
Thank you, such a quick response. Thanks man

**Comment by qiangdavidliu** [comment]
@bitsofinfo give 1.4.10-rc.1 a try and see if it fixes your issue?

**Comment by bitsofinfo** [comment]
Yes I ran the 1.4.10-rc.1 in a debugger in my app and now it properly invokes `createSystemSslCM()`  when `buildLegacy` is invoked. 

Quick question, what would be the best strategy to have this use a custom HostnameVerifier? I don't see a way to configure that

**Comment by bitsofinfo** [comment]
@Jumpy-Squirrel does this solve your issue at: https://github.com/spring-cloud/spring-cloud-netflix/issues/1077
