### ISSUE TITLE
IndexOutOfBounds Exception thrown repeatedly when Eureka has no EIPs containing "ec2-"

### ISSUE THREAD

**Issue by robertnosburn** [Netflix/eureka#818]
The EIPManager has a running task that looks to bind Eureka to EIPs.  In our case we are writing an application which is hosted in AWS but will not be publicly available and will be accessible ONLY from our corporate network.

We have an AWS Direct Connect to our corporate environment.  My EC2 container running my docker images, including Eureka, does not have a public nor elastic IP address.  In this case the only "ec2Urls" value is "http://localhost:8761".

EIPManager.getEIPsFromServiceUrls(List<String> ec2Urls) (line:346-349) does not handle this case and line 347 will throw:
java.lang.StringIndexOutOfBoundsException: String index out of range: -4
        at java.lang.String.substring(String.java:1967) ~[na:1.8.0_91]
        at com.netflix.eureka.aws.EIPManager.getEIPsFromServiceUrls(EIPManager.java:342) ~[eureka-core-1.4.6.jar!/:1.4.6]
        at com.netflix.eureka.aws.EIPManager.getEIPsForZoneFromConfig(EIPManager.java:322) ~[eureka-core-1.4.6.jar!/:1.4.6]
        at com.netflix.eureka.aws.EIPManager.getCandidateEIPs(EIPManager.java:304) ~[eureka-core-1.4.6.jar!/:1.4.6]
        at com.netflix.eureka.aws.EIPManager.isEIPBound(EIPManager.java:157) ~[eureka-core-1.4.6.jar!/:1.4.6]
        at com.netflix.eureka.aws.EIPManager$EIPBindingTask.run(EIPManager.java:412) ~[eureka-core-1.4.6.jar!/:1.4.6]
        at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_91]
        at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_91]

I propose a check to ensure that the index is greater than -1 before parsing the substrings.

See #819  as a potential fix.

Thanks,

Robert

**Comment by qiangdavidliu** [comment]
Hi @robertnosburn thank you for the PR. Looking at your usecase, it seems like what you would prefer is that the EIPBinder not run at all?

Eureka servers need to have fixed IPs, and EIP is one mechanism that we use to guarantee that in a cloud environment. However if you are able to guarantee that via some other mechanism, then possibly a better way to disable the errors from the EIPBinder is to not initialize the EIPBinder at all.

Eureka server currently support a configuration AwsBinder strategy (see https://github.com/Netflix/eureka/blob/master/eureka-core/src/main/java/com/netflix/eureka/aws/AwsBinderDelegate.java) where configuration (eureka. awsBindingStrategy=<EIP, ROUTE53, ENI>) can be used to define the binder type. What about a proposal that we add a fourth option (NOOP for a no-op binder) to that set of binders, which you can then configure via properties in your setup?

**Comment by robertnosburn** [comment]
Hi David,

I think that you are correct, I do not have any EIPs and so the EIPBinder would be unnecessary.  My Eureka runs in a docker container in an ec2 instance with a loadbalancer and a route-53 entry pointing to it.  This is how it's getting a fixed IP.  My microservices with Eureka clients know the location of the Eureka server by it's route-53 cname.

Looking through the code I also saw "e-ipbind-rebind-retries", which I tried setting to 0 in my application.yml both as 
`eureka:`
`    e-ipbind-rebind-retries: 0`
`  e-ipbinding-retry-interval-ms-when-unbound: 86400000`

and 
`eureka:`
`  server:`
`    e-ipbind-rebind-retries: 0`
`    e-ipbinding-retry-interval-ms-when-unbound: 86400000`

It looked as though this would allow the Binder to run once per day and not actually try to do the bind, but for some reason these values weren't getting picked up.

So yes, if I could persuade the EIPBinder to not run, that would be ideal.

As a side note, I think that my PR should still stand, it's probably not a bad idea to validate an index before using it in a substring, don't you think?

Thanks and Regards

**Comment by robertnosburn** [comment]
David,

I found the "eureka.server.binding-strategy" and set it to route53.  This causes a NPE on the EurekaController:

2016-07-20 23:44:54.878 ERROR 5 --- [nio-8761-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
        at org.springframework.cloud.netflix.eureka.server.EurekaController.getServerContext(EurekaController.java:143) ~[spring-cloud-netflix-eureka-server-1.1.4.RELEASE.jar!/:1.1.4.RELEASE]
        at org.springframework.cloud.netflix.eureka.server.EurekaController.getRegistry(EurekaController.java:139) ~[spring-cloud-netflix-eureka-server-1.1.4.RELEASE.jar!/:1.1.4.RELEASE]

Thoughts?
Thanks,

**Comment by qiangdavidliu** [comment]
@robertnosburn I buy your point, thanks. Have merged your PR in. As for the route53binder, let me take a look at that. We don't actually use that binder optional at Netflix and it was contributed to us by an external user, so it may have quirks that's specific for their use case.

**Comment by robertnosburn** [comment]
David,

Digging a little further, the actual exception is:
java.lang.RuntimeException: Cannot bootstrap eureka server :
        at org.springframework.cloud.netflix.eureka.server.EurekaServerBootstrap.contextInitialized(EurekaServerBootstrap.java:87) ~[spring-cloud-netflix-eureka-server-1.1.4.RELEASE.jar!/:1.1.4.RELEASE]
        at org.springframework.cloud.netflix.eureka.server.EurekaServerInitializerConfiguration$1.run(EurekaServerInitializerConfiguration.java:70) ~[spring-cloud-netflix-eureka-server-1.1.4.RELEASE.jar!/:1.1.4.RELEASE]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
Caused by: java.lang.NoSuchMethodError: com.amazonaws.AmazonWebServiceRequest.copyPrivateRequestParameters()Ljava/util/Map;
        at com.amazonaws.services.route53.AmazonRoute53Client.invoke(AmazonRoute53Client.java:1544) ~[aws-java-sdk-route53-1.9.3.jar!/:na]
        at com.amazonaws.services.route53.AmazonRoute53Client.listHostedZones(AmazonRoute53Client.java:382) ~[aws-java-sdk-route53-1.9.3.jar!/:na]
        at com.netflix.eureka.aws.Route53Binder.getHostedZone(Route53Binder.java:238) ~[eureka-core-1.4.9.jar!/:1.4.9]
        at com.netflix.eureka.aws.Route53Binder.getResourceRecordSetWithHostedZone(Route53Binder.java:212) ~[eureka-core-1.4.9.jar!/:1.4.9]
        at com.netflix.eureka.aws.Route53Binder.doBind(Route53Binder.java:109) ~[eureka-core-1.4.9.jar!/:1.4.9]
        at com.netflix.eureka.aws.Route53Binder.start(Route53Binder.java:89) ~[eureka-core-1.4.9.jar!/:1.4.9]

However that method exists in the 1.9.3 version of the aws-sdk-core jar.

BUT..

A dependency:tree on my project reveals:
[INFO] |  |  +- com.netflix.eureka:eureka-core:jar:1.4.9:compile
[INFO] |  |  |  +- com.amazonaws:aws-java-sdk-core:jar:1.10.30:runtime
[INFO] |  |  |  +- com.amazonaws:aws-java-sdk-ec2:jar:1.10.30:runtime
[INFO] |  |  |  +- com.amazonaws:aws-java-sdk-autoscaling:jar:1.9.3:runtime
[INFO] |  |  |  +- com.amazonaws:aws-java-sdk-sts:jar:1.9.3:runtime
[INFO] |  |  |  +- com.amazonaws:aws-java-sdk-route53:jar:1.9.3:runtime

I have performed a thorough search and I cannot see any reason why v1.10.30 of ec2 and core should be included, instead of the 1.9.3, as specified in the gradle files in tag v1.4.9

Thanks,

**Comment by ibaiul** [comment]
@robertnosburn, @qiangdavidliu   I have a problem with aws-java-sdk-core:jar:1.10.30:runtime and aws-java-sdk-ec2:jar:1.10.30:runtime dependencies as well.
Note:
I am using aws-java-sdk-sqs:1.10.72 which depends on aws-java-sdk-core:jar:1.10.72
I am using eureka-core:jar:1.4.10 which depends on aws-java-sdk-core:jar:1.9.3 and aws-java-sdk-ec2:jar:1.9.3
Dependency tree for -Dincludes=com.amazonaws:
[INFO] |  \- com.amazonaws:aws-java-sdk-sqs:jar:1.10.72:compile
[INFO] |     \- (com.amazonaws:aws-java-sdk-core:jar:1.10.30:compile - version managed from 1.10.72; omitted for duplicate)
[INFO] +- org.springframework.cloud:spring-cloud-starter-eureka:jar:1.1.5.RELEASE:compile
[INFO] |  \- com.netflix.eureka:eureka-core:jar:1.4.10:compile
[INFO] |     +- (com.amazonaws:aws-java-sdk-core:jar:1.10.30:runtime - version managed from 1.9.3; omitted for duplicate)
[INFO] |     +- com.amazonaws:aws-java-sdk-ec2:jar:1.10.30:runtime (version managed from 1.9.3)
[INFO] |     |  \- (com.amazonaws:aws-java-sdk-core:jar:1.10.30:runtime - version managed from 1.9.3; omitted for duplicate)
[INFO] |     +- com.amazonaws:aws-java-sdk-autoscaling:jar:1.9.3:runtime
[INFO] |     |  \- (com.amazonaws:aws-java-sdk-core:jar:1.10.30:runtime - version managed from 1.9.3; omitted for duplicate)
[INFO] |     +- com.amazonaws:aws-java-sdk-sts:jar:1.9.3:runtime
[INFO] |     |  \- (com.amazonaws:aws-java-sdk-core:jar:1.10.30:runtime - version managed from 1.9.3; omitted for duplicate)
[INFO] |     \- com.amazonaws:aws-java-sdk-route53:jar:1.9.3:runtime
[INFO] |        \- (com.amazonaws:aws-java-sdk-core:jar:1.10.30:runtime - version managed from 1.9.3; omitted for duplicate)

Which causes java.lang.ClassNotFoundException: com.amazonaws.ClientConfigurationFactory

When I explicitly declare the dependency aws-java-sdk-core:1.10.72 it fixes my problem with the aws-java-sdk-core dependency and I can run my application, but the dependency tree still shows that something is forcing the version aws-java-sdk-ec2:jar:1.10.30

[INFO] |  \- com.amazonaws:aws-java-sdk-sqs:jar:1.10.72:compile
[INFO] |     \- (com.amazonaws:aws-java-sdk-core:jar:1.10.72:compile - omitted for duplicate)
[INFO] +- org.springframework.cloud:spring-cloud-starter-eureka:jar:1.1.5.RELEASE:compile
[INFO] |  \- com.netflix.eureka:eureka-core:jar:1.4.10:compile
[INFO] |     +- (com.amazonaws:aws-java-sdk-core:jar:1.10.72:runtime - version managed from 1.9.3; omitted for duplicate)
[INFO] |     +- com.amazonaws:aws-java-sdk-ec2:jar:1.10.30:runtime (version managed from 1.9.3)
[INFO] |     |  \- (com.amazonaws:aws-java-sdk-core:jar:1.10.72:runtime - version managed from 1.10.30; omitted for duplicate)
[INFO] |     +- com.amazonaws:aws-java-sdk-autoscaling:jar:1.9.3:runtime
[INFO] |     |  \- (com.amazonaws:aws-java-sdk-core:jar:1.10.72:runtime - version managed from 1.9.3; omitted for duplicate)
[INFO] |     +- com.amazonaws:aws-java-sdk-sts:jar:1.9.3:runtime
[INFO] |     |  \- (com.amazonaws:aws-java-sdk-core:jar:1.10.72:runtime - version managed from 1.9.3; omitted for duplicate)
[INFO] |     \- com.amazonaws:aws-java-sdk-route53:jar:1.9.3:runtime
[INFO] |        \- (com.amazonaws:aws-java-sdk-core:jar:1.10.72:runtime - version managed from 1.9.3; omitted for duplicate)

I took a look at the gradle and pom files of eureka-core:1.4.10 and both declare dependencies to aws-java-sdk-core:1.9.3 and aws-java-sdk-ec2:1.9.3 so I don't know what is forcing the version 1.10.30

**Comment by qiangdavidliu** [comment]
@ibaiul can you double check to see that all of your aws-java-sdk-* dependencies are at the exact same patch version? Misalignment between the aws java sdk jar can cause these kind of errors.

**Comment by vikrantch-hk** [comment]
@qiangdavidliu @robertnosburn I have similar requirement where I dont want any EIP binder is there a way to stop EIPManager
