### ISSUE TITLE
my eureka server cluster have a exception

### ISSUE THREAD

**Issue by lijunyong** [Netflix/eureka#829]
2016-08-08 17:18:08.999 DEBUG 12076 --- [nio-7001-exec-7] o.a.coyote.http11.Http11NioProcessor     : Error parsing HTTP request header

java.io.EOFException: Unexpected EOF read on the socket
	at org.apache.coyote.http11.InternalNioInputBuffer.fill(InternalNioInputBuffer.java:152) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.coyote.http11.AbstractNioInputBuffer.parseRequestLine(AbstractNioInputBuffer.java:190) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1009) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672) [tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502) [tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458) [tomcat-embed-core-8.0.33.jar:8.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.33.jar:8.0.33]

is it normal?

**Comment by qiangdavidliu** [comment]
Hi @lijunyong what environment (tomcat version etc) are you trying to run the server under? Thanks.

**Comment by lijunyong** [comment]
@qiangdavidliu tomcat 8.0.33

**Comment by qiangdavidliu** [comment]
Hi @lijunyong we do have tomcat8 servers running as well, but I have not been able to repro this issue. Are you still seeing the problem? It might also be worthwhile asking this in the google group to see if the community has any idea. Thanks.
