### ISSUE TITLE
help！help！when eureka client  OOM happened，but eureka server’s app status not down

### ISSUE THREAD

**Issue by zhudan** [Netflix/eureka#888]
when eureka client  OOM happened，but eureka server’s app status not down，not down。。。。。；

Caused by: java.lang.OutOfMemoryError: unable to create new native thread。

<spring-cloud.version>Brixton.M5</spring-cloud.version>

`2017-01-14 16:25:44.855 ERROR http-nio-10.161.175.42-9512-ClientPoller-0  org.apache.tomcat.util.net.NioEndpoint[log:182] -
java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method) [na:1.8.0_65]
        at java.lang.Thread.start(Thread.java:714) [na:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950) ~[na:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1368) ~[na:1.8.0_65]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:161) ~[tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:141) ~[tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.apache.tomcat.util.net.NioEndpoint.processSocket(NioEndpoint.java:621) ~[tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.apache.tomcat.util.net.NioEndpoint$Poller.processKey(NioEndpoint.java:1113) ~[tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.apache.tomcat.util.net.NioEndpoint$Poller.run(NioEndpoint.java:1071) ~[tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]`

**Comment by spencergibb** [comment]
This is not the repo for Spring Cloud issues
