### ISSUE TITLE
eureka-client : Incorrect jackson-annotations version in POM/Build.gradle

### ISSUE THREAD

**Issue by sameekb** [Netflix/eureka#924]
Hi Team,

The master branch **eureka-client** is dependent on **jackson-annotations** 2,5.4. But during runtime following **NoClassDefFoundError** is thrown. Changing the version of  jackson-annotations to **2.8.3** in my POM fixed the issue. Pls fix it your codebase.

`
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonInclude$Value
	at com.fasterxml.jackson.databind.cfg.MapperConfig.<clinit>(MapperConfig.java:45)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:543)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:460)
	at com.netflix.discovery.converters.EurekaJacksonCodec.<init>(EurekaJacksonCodec.java:111)
	at com.netflix.discovery.converters.EurekaJacksonCodec.<clinit>(EurekaJacksonCodec.java:92)
	at com.netflix.discovery.converters.wrappers.CodecWrappers$LegacyJacksonJson.<init>(CodecWrappers.java:285)
	at com.netflix.discovery.converters.wrappers.CodecWrappers.create(CodecWrappers.java:125)
	at com.netflix.discovery.converters.wrappers.CodecWrappers.getEncoder(CodecWrappers.java:75)
	at com.netflix.discovery.converters.wrappers.CodecWrappers.getEncoder(CodecWrappers.java:66)
	at com.netflix.discovery.provider.DiscoveryJerseyProvider.<init>(DiscoveryJerseyProvider.java:68)
	at com.netflix.discovery.shared.transport.jersey.EurekaJerseyClientImpl$EurekaJerseyClientBuilder$MyDefaultApacheHttpClient4Config.<init>(EurekaJerseyClientImpl.java:194)
	at com.netflix.discovery.shared.transport.jersey.EurekaJerseyClientImpl$EurekaJerseyClientBuilder.build(EurekaJerseyClientImpl.java:170)
	at com.netflix.discovery.shared.transport.jersey.JerseyEurekaHttpClientFactory$JerseyEurekaHttpClientFactoryBuilder.buildLegacy(JerseyEurekaHttpClientFactory.java:197)
	at com.netflix.discovery.shared.transport.jersey.JerseyEurekaHttpClientFactory$JerseyEurekaHttpClientFactoryBuilder.build(JerseyEurekaHttpClientFactory.java:178)
	at com.netflix.discovery.shared.transport.jersey.JerseyEurekaHttpClientFactory.create(JerseyEurekaHttpClientFactory.java:135)
	at com.netflix.discovery.shared.transport.jersey.Jersey1TransportClientFactories.newTransportClientFactory(Jersey1TransportClientFactories.java:48)
	at com.netflix.discovery.DiscoveryClient.scheduleServerEndpointTask(DiscoveryClient.java:454)
	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:392)
	... 6 more
`

Regards,
Sameek

**Comment by qiangdavidliu** [comment]
Hi @sameekb do you have other dependencies in you application that bumped jackson version 2.8.3? Jackson have a family of jars that need to be in sync with versions.

**Comment by sameekb** [comment]
Hi @qiangdavidliu,
There is no other transitive dependency on jackson version 2.8.3.

**Comment by sameekb** [comment]
Hi @qiangdavidliu ,

**eureka-client 1.6.2** got built using  **jackson-annotations 2.5.4**
